#!/usr/bin/env python3
"""Generate runtime i18n C++ tables from main/i18n/catalog.json.

Usage:
  python3 scripts/gen_i18n.py [--catalog PATH] [--output PATH]

Output: main/i18n/i18n_strings_gen.h (enum + per-locale string tables).
Adding a language: append to catalog.json "locales" and each string entry,
then re-run this script (or rebuild — CMake wires it as a custom command).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys


def c_escape(s: str) -> str:
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif o < 32:
            out.append(f"\\x{o:02x}")
        else:
            out.append(ch)
    return "".join(out)


def locale_token(locale_id: str) -> str:
    # zh-CN -> ZhCN, en-US -> EnUS, ja-JP -> JaJP
    parts = re.split(r"[-_]", locale_id)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def validate(doc: dict) -> None:
    if "locales" not in doc or "strings" not in doc:
        raise ValueError("catalog.json must have 'locales' and 'strings'")
    locales = [x["id"] for x in doc["locales"]]
    if not locales:
        raise ValueError("no locales defined")
    keys = set()
    for i, entry in enumerate(doc["strings"]):
        key = entry.get("key")
        if not key or not re.fullmatch(r"[A-Z][A-Z0-9_]*", key):
            raise ValueError(f"string[{i}] invalid key: {key!r}")
        if key in keys:
            raise ValueError(f"duplicate key: {key}")
        keys.add(key)
        for loc in locales:
            if loc not in entry or not isinstance(entry[loc], str):
                # allow missing → fallback to default_locale / zh-CN / first
                pass


def generate(catalog_path: str, output_path: str) -> None:
    with open(catalog_path, "r", encoding="utf-8") as f:
        doc = json.load(f)
    validate(doc)

    locales = doc["locales"]
    locale_ids = [x["id"] for x in locales]
    default_locale = doc.get("default_locale", locale_ids[0])
    if default_locale not in locale_ids:
        default_locale = locale_ids[0]
    strings = doc["strings"]

    lines: list[str] = []
    lines.append("// Auto-generated by scripts/gen_i18n.py — DO NOT EDIT.")
    lines.append("// Source: main/i18n/catalog.json")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace I18n {")
    lines.append("")
    lines.append("enum class Locale : uint8_t {")
    for i, loc in enumerate(locale_ids):
        tok = locale_token(loc)
        comma = "," if i + 1 < len(locale_ids) else ""
        lines.append(f"    {tok} = {i}{comma}  // {loc}")
    lines.append("};")
    lines.append("")
    lines.append(f"constexpr size_t kLocaleCount = {len(locale_ids)};")
    lines.append(
        f"constexpr Locale kDefaultLocale = Locale::{locale_token(default_locale)};"
    )
    lines.append("")
    lines.append("enum class Str : uint16_t {")
    for i, entry in enumerate(strings):
        comma = "," if i + 1 < len(strings) else ""
        lines.append(f"    {entry['key']} = {i}{comma}")
    lines.append("};")
    lines.append("")
    lines.append(f"constexpr size_t kStringCount = {len(strings)};")
    lines.append("")
    lines.append("struct LocaleInfo {")
    lines.append("    Locale id;")
    lines.append("    const char* code;          // e.g. \"zh-CN\"")
    lines.append("    const char* native_name;   // e.g. \"简体中文\"")
    lines.append("    const char* english_name;  // e.g. \"Chinese (Simplified)\"")
    lines.append("};")
    lines.append("")
    lines.append("inline constexpr LocaleInfo kLocaleInfos[kLocaleCount] = {")
    for loc in locales:
        tok = locale_token(loc["id"])
        name = loc.get("name", loc["id"])
        en_name = loc.get("english_name", name)
        lines.append(
            f'    {{Locale::{tok}, "{c_escape(loc["id"])}", '
            f'"{c_escape(name)}", "{c_escape(en_name)}"}},'
        )
    lines.append("};")
    lines.append("")

    # msgid table (source / zh-CN) for gettext-style lookup
    lines.append("// Message ids = default-locale (usually zh-CN) text.")
    lines.append("inline constexpr const char* kMsgIds[kStringCount] = {")
    for entry in strings:
        src = entry.get(default_locale) or entry.get("zh-CN") or ""
        lines.append(f'    "{c_escape(src)}",')
    lines.append("};")
    lines.append("")

    for loc_id in locale_ids:
        tok = locale_token(loc_id)
        lines.append(
            f"inline constexpr const char* kStrings{tok}[kStringCount] = {{"
        )
        for entry in strings:
            text = entry.get(loc_id)
            if text is None:
                text = entry.get(default_locale) or entry.get("zh-CN") or ""
            lines.append(f'    "{c_escape(text)}",')
        lines.append("};")
        lines.append("")

    lines.append(
        "inline constexpr const char* const* kLocaleTables[kLocaleCount] = {"
    )
    for loc_id in locale_ids:
        tok = locale_token(loc_id)
        lines.append(f"    kStrings{tok},")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace I18n")
    lines.append("")

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    content = "\n".join(lines)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(
        f"Generated {output_path}: {len(strings)} strings × "
        f"{len(locale_ids)} locales"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    ap.add_argument(
        "--catalog",
        default=os.path.join(root, "main", "i18n", "catalog.json"),
    )
    ap.add_argument(
        "--output",
        default=os.path.join(root, "main", "i18n", "i18n_strings_gen.h"),
    )
    args = ap.parse_args()
    generate(args.catalog, args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
