#pragma once

// 副屏 USB 扩展编译期默认值（已从 Kconfig 下沉；运行时可调项见 usb_extend_prefs）。

#ifndef USB_EXTEND_DEFAULTS_H_
#define USB_EXTEND_DEFAULTS_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define USB_EXTEND_TUSB_VID 0x303A
#define USB_EXTEND_TUSB_PID 0x2986
#define USB_EXTEND_TUSB_MANUFACTURER "Espressif"
#define USB_EXTEND_TUSB_PRODUCT "Vendor"

// 与板级 DISPLAY_WIDTH/HEIGHT 一致（协议串 R{H}x{W}）
#define USB_EXTEND_SCREEN_HEIGHT 720
#define USB_EXTEND_SCREEN_WIDTH 720

#define USB_EXTEND_DEFAULT_JPEG_QUALITY 5
#define USB_EXTEND_DEFAULT_MAX_FPS 15
#define USB_EXTEND_DEFAULT_FRAME_LIMIT_B 150000

#define USB_EXTEND_USB_TASK_PRIORITY 6
#define USB_EXTEND_VENDOR_TASK_PRIORITY 5
#define USB_EXTEND_HID_TASK_PRIORITY 5
#define USB_EXTEND_TOUCH_TASK_PRIORITY 5

#define USB_EXTEND_HID_TOUCH_ENABLE 1
/* 仅扬声器 UAC（无 MIC），减轻 FS 口端点压力 */
#define USB_EXTEND_UAC_AUDIO_ENABLE 1

#define USB_EXTEND_LCD_BUF_COUNT 3
#define USB_EXTEND_LCD_BIT_PER_PIXEL 24

// 兼容旧 CONFIG_* 宏名，便于现有源文件少改
#ifndef CONFIG_TUSB_VID
#define CONFIG_TUSB_VID USB_EXTEND_TUSB_VID
#endif
#ifndef CONFIG_TUSB_PID
#define CONFIG_TUSB_PID USB_EXTEND_TUSB_PID
#endif
#ifndef CONFIG_TUSB_MANUFACTURER
#define CONFIG_TUSB_MANUFACTURER USB_EXTEND_TUSB_MANUFACTURER
#endif
#ifndef CONFIG_TUSB_PRODUCT
#define CONFIG_TUSB_PRODUCT USB_EXTEND_TUSB_PRODUCT
#endif
#ifndef CONFIG_USB_EXTEND_SCREEN_HEIGHT
#define CONFIG_USB_EXTEND_SCREEN_HEIGHT USB_EXTEND_SCREEN_HEIGHT
#endif
#ifndef CONFIG_USB_EXTEND_SCREEN_WIDTH
#define CONFIG_USB_EXTEND_SCREEN_WIDTH USB_EXTEND_SCREEN_WIDTH
#endif
#ifndef CONFIG_USB_TASK_PRIORITY
#define CONFIG_USB_TASK_PRIORITY USB_EXTEND_USB_TASK_PRIORITY
#endif
#ifndef CONFIG_VENDOR_TASK_PRIORITY
#define CONFIG_VENDOR_TASK_PRIORITY USB_EXTEND_VENDOR_TASK_PRIORITY
#endif
#ifndef CONFIG_HID_TASK_PRIORITY
#define CONFIG_HID_TASK_PRIORITY USB_EXTEND_HID_TASK_PRIORITY
#endif
#ifndef CONFIG_TOUCH_TASK_PRIORITY
#define CONFIG_TOUCH_TASK_PRIORITY USB_EXTEND_TOUCH_TASK_PRIORITY
#endif
#ifndef CONFIG_HID_TOUCH_ENABLE
#define CONFIG_HID_TOUCH_ENABLE USB_EXTEND_HID_TOUCH_ENABLE
#endif
#ifndef CONFIG_UAC_AUDIO_ENABLE
#define CONFIG_UAC_AUDIO_ENABLE USB_EXTEND_UAC_AUDIO_ENABLE
#endif
#ifndef CONFIG_EXAMPLE_LCD_BUF_COUNT
#define CONFIG_EXAMPLE_LCD_BUF_COUNT USB_EXTEND_LCD_BUF_COUNT
#endif
#define CONFIG_LCD_PIXEL_FORMAT_RGB888 1
#define CONFIG_LCD_PIXEL_FORMAT_RGB565 0

#ifdef __cplusplus
}
#endif

#endif  // USB_EXTEND_DEFAULTS_H_
