/*
 * Merged TinyUSB config for xingzhi-ai-395:
 * - Keep MSC (esp_tinyusb / virtual U-disk) class compiled in
 * - Enable Vendor + HID (+ optional UAC in descriptor) for USB extend screen
 * - Force Full-Speed: metalio-claw-4 only has USB OTG FS on GPIO24/25
 *
 * Note: tusb_config_uac.h is always included so usb_device_uac / TinyUSB audio
 * macros compile. Whether UAC appears in the USB config descriptor is gated by
 * CONFIG_UAC_AUDIO_ENABLE (defaults.h).
 */
#pragma once

#include "tusb_option.h"
#include "sdkconfig.h"
#include "esp_assert.h"
#include "usb_extend_defaults.h"
#include "uac_config.h"
#include "uac_descriptors.h"
#include "tusb_config_uac.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef CONFIG_TINYUSB_CDC_ENABLED
#define CONFIG_TINYUSB_CDC_ENABLED 0
#endif
#ifndef CONFIG_TINYUSB_CDC_COUNT
#define CONFIG_TINYUSB_CDC_COUNT 0
#endif
#ifndef CONFIG_TINYUSB_MSC_ENABLED
#define CONFIG_TINYUSB_MSC_ENABLED 0
#endif
#ifndef CONFIG_TINYUSB_HID_COUNT
#define CONFIG_TINYUSB_HID_COUNT 0
#endif
#ifndef CONFIG_TINYUSB_MIDI_COUNT
#define CONFIG_TINYUSB_MIDI_COUNT 0
#endif
#ifndef CONFIG_TINYUSB_VENDOR_COUNT
#define CONFIG_TINYUSB_VENDOR_COUNT 0
#endif
#ifndef CONFIG_TINYUSB_NET_MODE_ECM_RNDIS
#define CONFIG_TINYUSB_NET_MODE_ECM_RNDIS 0
#endif
#ifndef CONFIG_TINYUSB_NET_MODE_NCM
#define CONFIG_TINYUSB_NET_MODE_NCM 0
#endif
#ifndef CONFIG_TINYUSB_DFU_MODE_DFU
#define CONFIG_TINYUSB_DFU_MODE_DFU 0
#endif
#ifndef CONFIG_TINYUSB_DFU_MODE_DFU_RUNTIME
#define CONFIG_TINYUSB_DFU_MODE_DFU_RUNTIME 0
#endif
#ifndef CONFIG_TINYUSB_BTH_ENABLED
#define CONFIG_TINYUSB_BTH_ENABLED 0
#define CONFIG_TINYUSB_BTH_ISO_ALT_COUNT 0
#endif
#ifndef CONFIG_TINYUSB_DEBUG_LEVEL
#define CONFIG_TINYUSB_DEBUG_LEVEL 0
#endif

#define CFG_TUD_ENABLED 1

/* Board PHY is Full-Speed only. */
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CONFIG_USB_HS 0
#define CFG_TUD_MAX_SPEED OPT_MODE_FULL_SPEED

#define CFG_TUD_DWC2_SLAVE_ENABLE 1

#ifdef CONFIG_TINYUSB_MODE_DMA
#define CFG_TUD_DWC2_DMA_ENABLE 1
#if CONFIG_CACHE_L1_CACHE_LINE_SIZE && CONFIG_SOC_CACHE_INTERNAL_MEM_VIA_L1CACHE
#define CFG_TUD_MEM_DCACHE_ENABLE 1
#define CFG_TUD_MEM_DCACHE_LINE_SIZE CONFIG_CACHE_L1_CACHE_LINE_SIZE
#define CFG_TUSB_MEM_SECTION \
    __attribute__((aligned(CONFIG_CACHE_L1_CACHE_LINE_SIZE))) DRAM_ATTR
#else
#define CFG_TUD_MEM_DCACHE_ENABLE 0
#define CFG_TUD_MEM_CACHE_ENABLE 0
#define CFG_TUSB_MEM_SECTION TU_ATTR_ALIGNED(4) DRAM_ATTR
#endif
#endif

#ifndef CFG_TUSB_OS
#define CFG_TUSB_OS OPT_OS_FREERTOS
#endif

#ifndef ESP_PLATFORM
#define ESP_PLATFORM 1
#endif

#if TU_CHECK_MCU(OPT_MCU_ESP32S2, OPT_MCU_ESP32S3, OPT_MCU_ESP32P4, OPT_MCU_ESP32S31)
#define CFG_TUSB_OS_INC_PATH freertos/
#endif

#ifndef CFG_TUSB_MEM_SECTION
#define CFG_TUSB_MEM_SECTION
#endif
#ifndef CFG_TUSB_MEM_ALIGN
#define CFG_TUSB_MEM_ALIGN TU_ATTR_ALIGNED(4)
#endif
#ifndef CFG_TUD_ENDPOINT0_SIZE
#define CFG_TUD_ENDPOINT0_SIZE 64
#endif

#define CFG_TUSB_DEBUG CONFIG_TINYUSB_DEBUG_LEVEL
#define CFG_TUSB_DEBUG_PRINTF esp_rom_printf

#ifndef CONFIG_TINYUSB_CDC_RX_BUFSIZE
#define CONFIG_TINYUSB_CDC_RX_BUFSIZE 64
#endif
#ifndef CONFIG_TINYUSB_CDC_TX_BUFSIZE
#define CONFIG_TINYUSB_CDC_TX_BUFSIZE 64
#endif
#ifndef CONFIG_TINYUSB_CDC_EP_BUFSIZE
#define CONFIG_TINYUSB_CDC_EP_BUFSIZE 64
#endif
#ifndef CONFIG_TINYUSB_MSC_BUFSIZE
#define CONFIG_TINYUSB_MSC_BUFSIZE 512
#endif
#ifndef CONFIG_TINYUSB_VENDOR_RX_BUFSIZE
#define CONFIG_TINYUSB_VENDOR_RX_BUFSIZE 640
#endif
#ifndef CONFIG_TINYUSB_VENDOR_TX_BUFSIZE
#define CONFIG_TINYUSB_VENDOR_TX_BUFSIZE 64
#endif
#ifndef CONFIG_TINYUSB_VENDOR_EPSIZE
#define CONFIG_TINYUSB_VENDOR_EPSIZE 64
#endif
#ifndef CONFIG_TINYUSB_DFU_BUFSIZE
#define CONFIG_TINYUSB_DFU_BUFSIZE 4096
#endif
#ifndef CONFIG_TINYUSB_NCM_OUT_NTB_BUFFS_COUNT
#define CONFIG_TINYUSB_NCM_OUT_NTB_BUFFS_COUNT 1
#endif
#ifndef CONFIG_TINYUSB_NCM_IN_NTB_BUFFS_COUNT
#define CONFIG_TINYUSB_NCM_IN_NTB_BUFFS_COUNT 1
#endif
#ifndef CONFIG_TINYUSB_NCM_OUT_NTB_BUFF_MAX_SIZE
#define CONFIG_TINYUSB_NCM_OUT_NTB_BUFF_MAX_SIZE 2048
#endif
#ifndef CONFIG_TINYUSB_NCM_IN_NTB_BUFF_MAX_SIZE
#define CONFIG_TINYUSB_NCM_IN_NTB_BUFF_MAX_SIZE 2048
#endif

#define CFG_TUD_CDC_RX_BUFSIZE CONFIG_TINYUSB_CDC_RX_BUFSIZE
#define CFG_TUD_CDC_TX_BUFSIZE CONFIG_TINYUSB_CDC_TX_BUFSIZE
#define CFG_TUD_CDC_EP_BUFSIZE CONFIG_TINYUSB_CDC_EP_BUFSIZE
#define CFG_TUD_MSC_BUFSIZE CONFIG_TINYUSB_MSC_BUFSIZE
#define CFG_TUD_MIDI_EP_BUFSIZE 64
#define CFG_TUD_MIDI_EPSIZE CFG_TUD_MIDI_EP_BUFSIZE
#define CFG_TUD_MIDI_RX_BUFSIZE 64
#define CFG_TUD_MIDI_TX_BUFSIZE 64

#define USB_VID CONFIG_TUSB_VID
#define USB_PID CONFIG_TUSB_PID
#define USB_MANUFACTURER CONFIG_TUSB_MANUFACTURER
#define USB_PRODUCT CONFIG_TUSB_PRODUCT

/* Extend-screen classes (always on when this header is used). */
#define CFG_TUD_VENDOR 1
#define VENDOR_BUF_SIZE 64
#define CFG_TUD_VENDOR_RX_BUFSIZE (VENDOR_BUF_SIZE * 10)
#define CFG_TUD_VENDOR_TX_BUFSIZE VENDOR_BUF_SIZE
#define CFG_TUD_VENDOR_EPSIZE VENDOR_BUF_SIZE

#if CONFIG_HID_TOUCH_ENABLE
#define CFG_TUD_HID 1
#define CFG_TUD_HID_EP_BUFSIZE 64
#else
#define CFG_TUD_HID 0
#endif

/* Keep other classes from esp_tinyusb Kconfig so MSC can still install. */
#define CFG_TUD_CDC CONFIG_TINYUSB_CDC_COUNT
#define CFG_TUD_MSC CONFIG_TINYUSB_MSC_ENABLED
#define CFG_TUD_MIDI CONFIG_TINYUSB_MIDI_COUNT
#define CFG_TUD_ECM_RNDIS CONFIG_TINYUSB_NET_MODE_ECM_RNDIS
#define CFG_TUD_NCM CONFIG_TINYUSB_NET_MODE_NCM
#define CFG_TUD_DFU CONFIG_TINYUSB_DFU_MODE_DFU
#define CFG_TUD_DFU_RUNTIME CONFIG_TINYUSB_DFU_MODE_DFU_RUNTIME
#define CFG_TUD_BTH CONFIG_TINYUSB_BTH_ENABLED
#define CFG_TUD_DFU_XFER_BUFSIZE CONFIG_TINYUSB_DFU_BUFSIZE
#define CFG_TUD_BTH_ISO_ALT_COUNT CONFIG_TINYUSB_BTH_ISO_ALT_COUNT
#define CFG_TUD_NCM_OUT_NTB_N CONFIG_TINYUSB_NCM_OUT_NTB_BUFFS_COUNT
#define CFG_TUD_NCM_IN_NTB_N CONFIG_TINYUSB_NCM_IN_NTB_BUFFS_COUNT
#define CFG_TUD_NCM_OUT_NTB_MAX_SIZE CONFIG_TINYUSB_NCM_OUT_NTB_BUFF_MAX_SIZE
#define CFG_TUD_NCM_IN_NTB_MAX_SIZE CONFIG_TINYUSB_NCM_IN_NTB_BUFF_MAX_SIZE

/* 仅扬声器时关掉 TinyUSB Audio EP IN，避免 0 通道 MIC 缓冲异常 */
#if CONFIG_UAC_AUDIO_ENABLE && (CONFIG_UAC_MIC_CHANNEL_NUM == 0)
#ifdef CFG_TUD_AUDIO_ENABLE_EP_IN
#undef CFG_TUD_AUDIO_ENABLE_EP_IN
#endif
#define CFG_TUD_AUDIO_ENABLE_EP_IN 0
#endif

#ifdef __cplusplus
}
#endif
